### ISSUE TITLE
Many papers missing in the MLOSS section

### ISSUE THREAD

**Issue by rmcantin** [JmlrOrg/webpage#28]
Hi,

I've seen that there are many papers missing in the MLOSS section, specially before 2015. They are still in the webpage, but the code link have disappeared.

For example: 
https://jmlr.csail.mit.edu/papers/v11/rasmussen10a.html
https://www.jmlr.org/papers/v15/martinezcantin14a.html

In the case, of BayesOpt, I think the old link was pointing to bitbucket who has deleted all mercurial repos recently. Could you update the code link? https://github.com/rmcantin/bayesopt

**Comment by fabianp** [comment]
Hi @rmcantin . I can do that if you make a pull request with a new version of the PDF (https://github.com/JmlrOrg/v15/tree/master/martinezcantin14a) since I don't have access to the sources of that paper

**Comment by rmcantin** [comment]
Done. I have also fixed the json file.

https://github.com/JmlrOrg/v15/pull/1

**Comment by rmcantin** [comment]
The webpage still doesn't show my fix. I think the problem is that I have updated v15, but the main repo is still pointing to an old commit of v15.

¡Gracias!

**Comment by fabianp** [comment]
oops, thanks for noticing

**Comment by fabianp** [comment]
I'll look into it

**Comment by rcurtin** [comment]
It seems this issue still exists---many papers before 2015 don't seem to be listed.  (I went looking for one today and was surprised to not find it.)

**Comment by fabianp** [comment]
thanks @rcurtin . Due to a recent migration, I think some papers are not correctly tagged as OSS papers. Is there any specific paper that is missing from the list? If I have a list of papers missing, then I can go and correct the issue

**Comment by rcurtin** [comment]
Well, I only came across the issue looking for the [mlpack paper](https://jmlr.org/papers/v14/curtin13a.html), but, I did get a whole list of all of them on archive.org:

https://web.archive.org/web/20170701191529/http://jmlr.org/mloss/

That should have everything from 2015 and back.  It looks like basically everything there should be included but isn't; I only see ~5 2015 and earlier papers on the current site.

Thanks for the response! :+1:

**Comment by fabianp** [comment]
OK I finally had the courage to fix this. I think all MLOSS papers are reflected at https://www.jmlr.org/mloss/ 

If not, please reopen the issue.

Thanks!

**Comment by rcurtin** [comment]
Thank you!  It looks great to me.  I had completely forgotten about this :smile:
